# Generated by Django 4.0.5 on 2022-06-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='camada',
            field=models.IntegerField(default=0),
        ),
    ]
